#!/bin/bash

# Logging function
log() {
  echo -e "\033[1;32m[+]\033[0m $1"
}

# Install Homebrew
if ! command -v brew &>/dev/null; then
  log "Installing Homebrew"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
  log "Homebrew already installed"
fi

# Install Homebrew bundle
log "Installing Homebrew bundle"
cd $HOME/.dotfiles
brew bundle

# Configure keystrokes for Neovim/VSCode
defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false

# Configure symlinks to configs
log "Symlinking dotfiles with Stow"
stow -d $HOME/.dotfiles/confs -t $HOME -R git neovim tmux zsh bat btop ncdu lazygit amfora ssh gnupg

# Create authorized keys file
touch ~/.ssh/authorized_keys
chmod 644 ~/.ssh/authorized_keys

# Set ZSH as default shell if not already set
if [[ $SHELL != '/bin/zsh' ]]; then
  log "Setting ZSH as default shell"
  chsh -s '/bin/zsh'
  # FIXME: Test on a new install, this might not work since the shell is not sourced
  fast-theme ~/.config/fsh/catppuccin-$CATPPUCCIN_FLAVOR
fi

# Configure FZF if not already configured in shell i.e. if ~/.fzf.zsh does not exist
if [[ ! -f ~/.fzf.zsh ]]; then
  log "Installing FZF shell utilities"
  $(brew --prefix)/opt/fzf/install --all --no-bash --no-fish
fi

# Build Bat theme cache
bat cache --build

# Install Neovim plugin dependencies
log "Installing Neovim plugin dependencies"

# Install Neovim Python provider
/opt/homebrew/bin/pip3 install pynvim --upgrade --user --break-system-packages
/opt/homebrew/bin/python3 -m pip install --upgrade --user pynvim --break-system-packages

# Install XCode Neovim tooling
sudo gem install xcodeproj
/opt/homebrew/bin/pip3 install pymobiledevice3 --upgrade --user --break-system-packages
